title: Victor Guirra
logo: /assets/imgs/68930494_2493374670754269_1093725739892604928_n.jpg
#description: text below image
#show_downloads: true
#theme: jekyll-theme-minimal
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
